services:
  kudago-service:
    build:
      dockerfile: Dockerfile
    container_name: kudago-service
    restart: unless-stopped
    env_file: .env
    ports:
      - '8080:8080'
    environment:
      DB_URL: $DB_URL
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
    depends_on:
      - kudago-db

  kudago-db:
    image: postgres:17
    container_name: kudago-db
    restart: unless-stopped
    env_file: .env
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME"]
      interval: 10s
      timeout: 5s