/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import lombok.extern.slf4j.Slf4j;
import org.example.reader.JsonCityReader;
import org.example.writer.XmlCityWriter;

import java.nio.file.Path;

@Slf4j
public class App {

    private static final Path jsonPath = Path.of("src/main/resources/json/city.json");
    private static final Path xmlPath = Path.of("src/main/resources/xml/city.xml");

    public static void main(String[] args) {
        JsonCityReader jsonCityParser = new JsonCityReader();
        XmlCityWriter xmlCityWriter = new XmlCityWriter();
        jsonCityParser.readCityFromFile(jsonPath)
                .ifPresentOrElse(
                        city -> {
                            xmlCityWriter.writeCityToFile(city, xmlPath);
                        },
                        () -> log.warn("City is null. Something went wrong"));
    }
}
