spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: db/changelog-master.xml
    enabled: true

  cache:
    type: caffeine
    time-to-live-seconds: 3600

resilience4j:
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        failure-rate-threshold: 50
        sliding-window-size: 10
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

rest:
  kudago-service:
    host: https://kudago.com/public-api/v1.4
    methods:
      categories:
        type: GET
        uri: /place-categories/
      locations:
        type: GET
        uri: /locations/
      events:
        type: GET
        uri: /events/

  currency-rate-service:
    host: http://www.cbr.ru/scripts
    methods:
      rates:
        type: GET
        uri: /XML_daily.asp

data-initialization:
  threads: 2
  period-seconds: 600
  enable: false

security:
  jwt:
    jwt-key: ${JWT_KEY:123456789}
    default-expiration: 600 # 10 minutes in seconds
    remember-me-expiration: 2592000 # 30 days in seconds
