rest:
    kudago-service:
        host: https://kudago.com/public-api/v1.4
        methods:
            categories:
                type: GET
                uri: /place-categories/
            locations:
                type: GET
                uri: /locations/
    currency-rate-service:
        host: http://www.cbr.ru/scripts
        methods:
            rates:
                type: GET
                uri: /XML_daily.asp
