rest:
    kudago-service:
        host: https://kudago.com/public-api/v1.4
        methods:
            categories:
                type: GET
                uri: /place-categories/
            locations:
                type: GET
                uri: /locations/
