name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Calculate test coverage
        run: ./gradlew jacocoTestReport

      - name: Static code analysis
        run: ./gradlew check

      - name: Build Docker image
        run: |
          docker build . -t my-app:${{ github.sha }}

      - name: Log in to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image to GitHub Packages
        run: |
          docker tag my-app:${{ github.sha }} ghcr.io/${{ github.repository }}/my-app:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}/my-app:${{ github.sha }}
