name: Gradle Package

on:
  push:
    branches:
      - main  # Adjust this if you want to target a different branch
  pull_request:
    branches:
      - main  # Run on pull requests targeting the main branch
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Run tests
        run: ./gradlew test

      - name: Calculate test coverage
        run: ./gradlew jacocoTestReport

      - name: Static code analysis
        run: ./gradlew checkstyleMain

      - name: Add coverage to PR
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/build/reports/jacocoReports/test/jacocoTestReport.xml,
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 20
          min-coverage-changed-files: 20
